import type { Account, Transaction, User } from '../types'

const CUSTOMER_ID = 'user-001'
const ADMIN_ID = 'admin-001'
const ACCOUNT_ID = 'acc-001'

export const SEED_USERS: User[] = [
  {
    id: ADMIN_ID,
    name: 'System Admin',
    email: 'admin@example.com',
    password: 'Admin@12345',
    role: 'admin',
    phone: '+91 98765 43210',
    account_number: '',
    account_type: '',
    currency: 'INR',
    status: 'active',
    created_at: '2024-01-15T00:00:00Z',
  },
  {
    id: CUSTOMER_ID,
    name: 'Alex Johnson',
    email: 'user@example.com',
    password: 'User@12345',
    role: 'customer',
    phone: '+91 91234 56789',
    account_number: '4821009384821',
    account_type: 'Savings Account',
    currency: 'INR',
    status: 'active',
    created_at: '2023-06-12T00:00:00Z',
  },
]

export const SEED_ACCOUNT: Account = {
  id: ACCOUNT_ID,
  user_id: CUSTOMER_ID,
  balance: 125450,
  available_balance: 125450,
  opening_balance: 125450,
  created_at: '2023-06-12T00:00:00Z',
}

function txn(
  partial: Omit<Transaction, 'account_id' | 'created_at' | 'updated_at'>,
): Transaction {
  const now = new Date().toISOString()
  return {
    account_id: ACCOUNT_ID,
    created_at: now,
    updated_at: now,
    ...partial,
  }
}

export const SEED_TRANSACTIONS: Transaction[] = [
  txn({
    id: 'txn-001',
    type: 'credit',
    amount: 80000,
    title: 'Salary',
    description: 'Monthly salary',
    merchant: '',
    sender: 'ABC Company',
    recipient: 'Alex Johnson',
    category: 'Income',
    reference: 'SAL-2026-0901',
    transaction_id: 'TXN-100001',
    date: '2026-09-01',
    time: '10:30 AM',
    status: 'completed',
    notes: 'August salary credit',
    balance_before: 45450,
    balance_after: 125450,
  }),
  txn({
    id: 'txn-002',
    type: 'debit',
    amount: 3499,
    title: 'Amazon',
    description: 'Online purchase',
    merchant: 'Amazon',
    sender: 'Alex Johnson',
    recipient: 'Amazon India',
    category: 'Shopping',
    reference: 'TXN-893472',
    transaction_id: 'TXN-100002',
    date: '2026-09-14',
    time: '6:45 PM',
    status: 'completed',
    notes: 'Electronics order',
    balance_before: 128949,
    balance_after: 125450,
  }),
  txn({
    id: 'txn-003',
    type: 'debit',
    amount: 850,
    title: 'Swiggy',
    description: 'Food delivery',
    merchant: 'Swiggy',
    sender: 'Alex Johnson',
    recipient: 'Swiggy',
    category: 'Food',
    reference: 'SWG-442891',
    transaction_id: 'TXN-100003',
    date: '2026-09-13',
    time: '8:20 PM',
    status: 'completed',
    notes: 'Dinner order',
    balance_before: 126300,
    balance_after: 125450,
  }),
  txn({
    id: 'txn-004',
    type: 'credit',
    amount: 15000,
    title: 'Freelance Payment',
    description: 'Design project payment',
    merchant: '',
    sender: 'Creative Studio Ltd',
    recipient: 'Alex Johnson',
    category: 'Income',
    reference: 'FL-2026-0910',
    transaction_id: 'TXN-100004',
    date: '2026-09-10',
    time: '2:15 PM',
    status: 'completed',
    notes: 'UI design milestone',
    balance_before: 111300,
    balance_after: 126300,
  }),
  txn({
    id: 'txn-005',
    type: 'debit',
    amount: 2500,
    title: 'Electricity Bill',
    description: 'Monthly utility payment',
    merchant: 'BESCOM',
    sender: 'Alex Johnson',
    recipient: 'BESCOM',
    category: 'Utilities',
    reference: 'BES-882910',
    transaction_id: 'TXN-100005',
    date: '2026-09-08',
    time: '11:00 AM',
    status: 'completed',
    notes: 'September bill',
    balance_before: 113800,
    balance_after: 111300,
  }),
  txn({
    id: 'txn-006',
    type: 'debit',
    amount: 1200,
    title: 'Uber',
    description: 'Cab ride to airport',
    merchant: 'Uber',
    sender: 'Alex Johnson',
    recipient: 'Uber India',
    category: 'Transport',
    reference: 'UBR-772341',
    transaction_id: 'TXN-100006',
    date: '2026-09-07',
    time: '5:30 AM',
    status: 'completed',
    notes: 'Airport transfer',
    balance_before: 115000,
    balance_after: 113800,
  }),
  txn({
    id: 'txn-007',
    type: 'credit',
    amount: 5000,
    title: 'Refund',
    description: 'Product return refund',
    merchant: 'Flipkart',
    sender: 'Flipkart',
    recipient: 'Alex Johnson',
    category: 'Refund',
    reference: 'REF-991234',
    transaction_id: 'TXN-100007',
    date: '2026-09-05',
    time: '3:45 PM',
    status: 'completed',
    notes: 'Returned headphones',
    balance_before: 110000,
    balance_after: 115000,
  }),
  txn({
    id: 'txn-008',
    type: 'debit',
    amount: 999,
    title: 'Netflix',
    description: 'Subscription renewal',
    merchant: 'Netflix',
    sender: 'Alex Johnson',
    recipient: 'Netflix India',
    category: 'Entertainment',
    reference: 'NFLX-202609',
    transaction_id: 'TXN-100008',
    date: '2026-09-04',
    time: '12:00 AM',
    status: 'completed',
    notes: 'Premium plan',
    balance_before: 110999,
    balance_after: 110000,
  }),
  txn({
    id: 'txn-009',
    type: 'debit',
    amount: 450,
    title: 'Pharmacy',
    description: 'Medicine purchase',
    merchant: 'Apollo Pharmacy',
    sender: 'Alex Johnson',
    recipient: 'Apollo Pharmacy',
    category: 'Health',
    reference: 'APL-334521',
    transaction_id: 'TXN-100009',
    date: '2026-09-03',
    time: '6:10 PM',
    status: 'completed',
    notes: 'Prescription medicines',
    balance_before: 111449,
    balance_after: 110999,
  }),
  txn({
    id: 'txn-010',
    type: 'credit',
    amount: 2500,
    title: 'Cashback',
    description: 'Credit card cashback',
    merchant: 'Velora Bank',
    sender: 'Velora Bank',
    recipient: 'Alex Johnson',
    category: 'Rewards',
    reference: 'CB-202609',
    transaction_id: 'TXN-100010',
    date: '2026-09-02',
    time: '9:00 AM',
    status: 'completed',
    notes: 'Quarterly cashback',
    balance_before: 108949,
    balance_after: 111449,
  }),
]
